# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  path_filter:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - "frontend/**"
            backend:
              - "backend/**"

  job_for_frontend:
    needs: path_filter
    runs-on: ubuntu-latest
    if: needs.path_filter.outputs.frontend == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci frontend

      - name: Run tests
        run: npm test frontend

      - name: Build project
        run: npm run build frontend

  job_for_backend:
    needs: path_filter
    runs-on: ubuntu-latest
    if: needs.path_filter.outputs.backend == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci backend

      - name: Run tests
        run: npm test backend

      - name: Build project
        run: npm run build backend
